### ISSUE TITLE
Reconnecting threaded consumers

### ISSUE THREAD

**Issue by thejuan** [eandersson/amqp-storm#10]
Is there any guidance for how to reconnect on lost connection when you have multiple consumers?
At the moment I have a channel per thread.
On the main thread I reconnect on error

<code>
if self.connection.is_closed:
                self.connection.open()
</code>

I restart each thread which opens a new channel and consumes.
I notice that after a reconnect it adds another heartbeat checker - each period i see multiple
"Checking for a heartbeat"

Thanks

**Comment by eandersson** [comment]
I do see some oddities, probably some work that can be done here. I might have to add some locking to connection open/closing. I'll also try to add a recommended strategy for re-connecting in the examples.

I pushed a the new version 1.2.6 a while ago to git, but I forgot to push to pypi that moved the heartbeat initialization down the chain. If you don't already have it, it might be worth a try for now.

**Comment by thejuan** [comment]
I have made some changes that seem to work. (I already lock on reconnection)
I always close the connection on error, to force heartbeat stop and it seems ok now.

**Comment by eandersson** [comment]
Glad you got it sorted. I am going to change the behavior of connections closed unexpectedly by having it use the default connection.close call, instead of the current custom routine, but not sure this would fix this behavior, as the connection can be closed on any thread, not necessarily the main thread.

**Comment by eandersson** [comment]
I found a race-condition in the Heartbeat code that is likely to have caused the issue you described. It should be fixed in the commit b79b468.
