### ISSUE TITLE
Properties and Headers

### ISSUE THREAD

**Issue by viniciuschiele** [eandersson/amqp-storm#2]
The value of some properties (i.e: message_id) are being returned as byte array, same thing for headers keys, they could be returned as string for easy use.

Thanks!

**Comment by eandersson** [comment]
Hey,

This is something that I have been looking into myself. The problem is that I use pamqp to decode the incoming messages, and by default it returns them as a byte array. I can easily fix this myself, but ideally I would like the behavior to be consistent with the pamqp output. I'll probably look into fixing this for the new major release.

**Comment by eandersson** [comment]
Hey,

I started working on amqp-storm 1.2.0 and one of the features I am looking to introduce is better use of the Message class. I want to keep the default behavior of returning a raw dict or tuple, but allow access to higher level objects. In this case a Message class that automatically handles the decoding of the message.

Not sure if this will be the final implementation, but you can take a look at an example here:
https://github.com/eandersson/amqp-storm/blob/1.2.0/examples/advanced_consumer.py

If you set to_tuple to false, and access the Message class using for example message.properties you should find that all objects have been decoded.

Let me know @viniciuschiele what you think.

**Comment by viniciuschiele** [comment]
Hi,

The example is not available any more.
I was wondering whether one of my property items was a dict, will it be decoded too? (In this case the key is also encoded).

Cheers

**Comment by eandersson** [comment]
@viniciuschiele: I still need to add some sort of recursive fix, and I'll add the decoding to key's as well.

Ah yea my bad, renamed the example.
https://github.com/eandersson/amqp-storm/blob/master/examples/simple_consumer.py

**Comment by eandersson** [comment]
@viniciuschiele I added a simple test showcasing the changes I did per your feedback.
https://github.com/eandersson/amqp-storm/blob/master/tests/message_tests.py#L39

Basically if you use the property Message.properties (or Message.method) you should get back a str assuming that it can be converted, but this does not apply to to_dict or to_tuple that is used internally. 

If you want to use the native Message object when consuming you also have to use the new to_tuple=False parameter.

e.g.
```
channel.start_consuming(to_tuple=False)
channel.process_data_events(to_tuple=False)
```

**Comment by viniciuschiele** [comment]
Hi @eandersson 

This new version looks very good, it is working well here and I could remove many lines of code using this version.

Thanks for that.

**Comment by eandersson** [comment]
Perfect. Let me know if you run into any new issues.
