### ISSUE TITLE
Exception: 'Deliver' object has no attribute 'body_size'

### ISSUE THREAD

**Issue by viniciuschiele** [eandersson/amqp-storm#3]
I have been experiencing a strange error, just for some messages I got this error:

'Deliver' object has no attribute 'body_size'
channel.py (line: 253)

I looked at self._inbound and I saw some Deliver objects in sequence instead of Deliver/ContentHeader/ContentBody

![amqp-storm](https://cloud.githubusercontent.com/assets/392495/7298024/c9584ed2-e9c4-11e4-9ef2-446a1e48db0d.png)

The messages are being sent to the queue by another project in another language, so I have no clue why it is happening.

**Comment by eandersson** [comment]
Hey! I'll take a look tonight and sort it out.

**Comment by eandersson** [comment]
@viniciuschiele: 

I don't see why, or how you could have received two Deliver frames in a row, that must be a bug in RabbitMQ. What version are you running? Are you running multiple threads when consuming?

I pushed a minor fix, do you think you could clone the repo and try it out and if possible could you make sure that you are not losing any messages?

**Comment by viniciuschiele** [comment]
RabbitMQ: 3.4.4

I'm not running multiple threads, I just created one thread to call channel.start_consuming()

Yes I can clone it but did you push your code? The last commit was 4 days ago

**Comment by eandersson** [comment]
I forgot to run git pull. It should be there now! =]

**Comment by eandersson** [comment]
@viniciuschiele Could you show me the contents of the two Deliver objects if it happens again?

**Comment by viniciuschiele** [comment]
Same thing happened, some times I receive Deliver/ContentHeader/ContentHeader or Deliver/ContentHeader/Deliver... it seems to be unordered.

![amqp-storm2](https://cloud.githubusercontent.com/assets/392495/7301698/34269e6e-e9dc-11e4-839e-a24434ddc0e9.png)

**Comment by viniciuschiele** [comment]
I put no_ack=True to test and I lost all messages from the queue so I can't reproduce it again, I will have to wait until the other system to send new invalid messages, it might take some time :/

Next time I will try to set the prefetch_count

**Comment by eandersson** [comment]
My guess is that it was a bug, for some reason only the first frame (out of 3) was received from RabbitMQ. I guess it could have been a network issue? 

With the patch I gave you it shouldn't crash, but if you have no_ack set to true, it could mean that you lose a message which is bad.

**Comment by viniciuschiele** [comment]
@eandersson Today I was able to reproduce this issue again, so I just set prefetch_count=1 and it have solved this issue. Next time I will increase prefetch_count to see what will happen.

Thanks!

**Comment by eandersson** [comment]
So I am pretty sure this is a RabbitMQ bug. Do you know what language and library is used to send the messages? Any details I could use to try to reproduce this would be helpful.

**Comment by viniciuschiele** [comment]
@eandersson I set prefetch_count  to 10 and it has worked well, to me it solves this issue, I think you could close it.

I don't know what library they are using to send the messages because this software is not ours.

Thanks for your time.

**Comment by eandersson** [comment]
No worries @viniciuschiele. Thanks for the report and glad you got it sorted.
