### ISSUE TITLE
localhost on OSX

### ISSUE THREAD

**Issue by viniciuschiele** [eandersson/amqp-storm#7]
Hi,

In this last version the url localhost does not work anymore on OS X (Ubuntu works fine), I got Connection Refused.
url: amqp://guest:guest@localhost/

Below the line which raise the exception:
```python
# file io.py
sock.connect(sock_address_tuple[4])
```
```python
sock_address_tuple[4] = ('::1', 5672, 0, 0)
```
If I use 127.0.0.1 rather than localhost it works well.

Cheers!

**Comment by eandersson** [comment]
Interesting. Could you post the trace back?

**Comment by eandersson** [comment]
Let me know if this commit solves your issue @viniciuschiele

**Comment by viniciuschiele** [comment]
Sorry for my late reply, these commits has fixed my issue.

Thanks a lot.

**Comment by eandersson** [comment]
Cool. I'll push a new build out to pypi today.
