### ISSUE TITLE
Fanout Exchange

### ISSUE THREAD

**Issue by ouziel-slama** [eandersson/amqp-storm#9]
Hello,

I'am trying to set up a `fanout` exchange to deliver a message to multiple consumers. I didn't find any example for that. I tried to write something similar to the `pika` example here https://www.rabbitmq.com/tutorials/tutorial-three-python.html. The code doesn't raise any error, but only the first consumer receives message. Here the relevant code:

Publisher:
```
self.connection = amqpstorm.Connection(self.host, self.username, self.password)
self.channel = self.connection.channel()
self.channel.exchange.declare(exchange=self.exchange, exchange_type='fanout')
self.channel.queue.declare(self.queue, durable=True)
self.channel.queue.bind(self.queue, exchange=self.exchange)
self.channel.confirm_deliveries()
self.channel.basic.publish(body=body, routing_key=self.queue, mandatory=True, exchange=self.exchange)
```
Consumer:
```
self.connection = amqpstorm.Connection(self.host, self.username, self.password)
self.channel = self.connection.channel()
self.channel.exchange.declare(exchange=self.exchange, exchange_type='fanout')
self.channel.queue.declare(self.queue, durable=True)
self.channel.queue.bind(self.queue, exchange=self.exchange)
self.channel.confirm_deliveries()
self.channel.basic.consume(self.queue, no_ack=False)
```

Is the correct code to set up a `fanout` exchange ? I tried with `no_ack=False` and `no_ack=True`, and different variants of the code above, but I always get the same thing: no error, but only the first consumer receives the message.

Thank you in advance for your help.

**Comment by eandersson** [comment]
Hey,

If you have multiple consumers consuming from the same queue, only one of them will get the message. You will need to use different queues for each consumer, as an example in the pika example this is done using channel.queue_declare(exclusive=True), but you could simple use different names for the various consumers; e.g. queue1 and queue2.

In amqpstorm you would implement an exclusive queue like this.
```
result = self.channel.queue.declare(durable=True, exclusive=True)
self.queue = result['queue']
```

I hope this helps. =]

**Comment by ouziel-slama** [comment]
Hey,

Ah yeah, got it!  Thank you very much for your answer, will try that now!

Best

**Comment by eandersson** [comment]
No worries. Let me know if you run in to any issues!

**Comment by ouziel-slama** [comment]
Works very well thank you!
